begin;

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

-- ============================================================
-- 1. RESEÑAS VERIFICADAS
-- ============================================================
create table if not exists public.book_reviews (
  id uuid primary key default gen_random_uuid(),
  book_id uuid not null references public.books(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  purchase_id uuid references public.book_purchases(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  title text,
  review text,
  verified_purchase boolean not null default false,
  helpful_count integer not null default 0 check (helpful_count >= 0),
  status text not null default 'published' check (status in ('pending','published','hidden','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (book_id, user_id)
);

create index if not exists book_reviews_book_status_idx
  on public.book_reviews(book_id, status, created_at desc);
create index if not exists book_reviews_user_idx
  on public.book_reviews(user_id, created_at desc);

create or replace function public.set_book_review_verified_purchase()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  matched_purchase uuid;
begin
  select bp.id
    into matched_purchase
  from public.book_purchases bp
  where bp.book_id = new.book_id
    and bp.user_id = new.user_id
    and lower(coalesce(bp.status, '')) in ('paid','completed','approved','succeeded')
  order by coalesce(bp.paid_at, bp.created_at) desc
  limit 1;

  new.purchase_id := matched_purchase;
  new.verified_purchase := matched_purchase is not null;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists book_reviews_verify_purchase on public.book_reviews;
create trigger book_reviews_verify_purchase
before insert or update of book_id, user_id, rating, title, review
on public.book_reviews
for each row execute function public.set_book_review_verified_purchase();

-- ============================================================
-- 2. EVENTOS DE MARKETPLACE / FUNNEL
-- ============================================================
create table if not exists public.marketplace_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  anonymous_id text,
  session_id text,
  book_id uuid references public.books(id) on delete cascade,
  event_type text not null,
  surface text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists marketplace_events_event_id_uidx
  on public.marketplace_events(event_id);
create index if not exists marketplace_events_book_type_time_idx
  on public.marketplace_events(book_id, event_type, occurred_at desc);
create index if not exists marketplace_events_user_time_idx
  on public.marketplace_events(user_id, occurred_at desc)
  where user_id is not null;
create index if not exists marketplace_events_session_idx
  on public.marketplace_events(session_id, occurred_at desc)
  where session_id is not null;

-- ============================================================
-- 3. EPUB PREFLIGHT
-- ============================================================
create table if not exists public.epub_preflight_reports (
  id uuid primary key default gen_random_uuid(),
  book_id uuid not null references public.books(id) on delete cascade,
  edition_id uuid references public.book_editions(id) on delete set null,
  source_sha256 text,
  epub_version text,
  layout text not null default 'unknown',
  score smallint not null check (score between 0 and 100),
  status text not null default 'warning' check (status in ('pass','warning','fail')),
  summary jsonb not null default '{}'::jsonb,
  findings jsonb not null default '[]'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists epub_preflight_book_time_idx
  on public.epub_preflight_reports(book_id, created_at desc);
create index if not exists epub_preflight_score_idx
  on public.epub_preflight_reports(score, status);

-- ============================================================
-- 4. VERSIONADO EDITORIAL
-- ============================================================
create table if not exists public.book_editorial_versions (
  id uuid primary key default gen_random_uuid(),
  book_id uuid not null references public.books(id) on delete cascade,
  edition_id uuid references public.book_editions(id) on delete set null,
  version_number integer not null check (version_number > 0),
  checksum_sha256 text,
  file_url text,
  change_notes text,
  preflight_report_id uuid references public.epub_preflight_reports(id) on delete set null,
  is_current boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (book_id, version_number)
);

create unique index if not exists book_editorial_versions_one_current_uidx
  on public.book_editorial_versions(book_id)
  where is_current;

create or replace function public.set_book_editorial_version_current()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.is_current then
    update public.book_editorial_versions
       set is_current = false
     where book_id = new.book_id
       and id <> new.id
       and is_current = true;
  end if;
  return new;
end;
$$;

drop trigger if exists book_editorial_versions_current on public.book_editorial_versions;
create trigger book_editorial_versions_current
after insert or update of is_current
on public.book_editorial_versions
for each row execute function public.set_book_editorial_version_current();

-- ============================================================
-- 5. MÉTRICAS VERIFICADAS
-- ============================================================
create or replace view public.book_verified_metrics as
with purchases as (
  select
    bp.book_id,
    count(*) filter (
      where lower(coalesce(bp.status,'')) in ('paid','completed','approved','succeeded')
    )::bigint as verified_sales_count,
    count(*) filter (
      where lower(coalesce(bp.status,'')) in ('refunded','revoked')
    )::bigint as refund_count,
    coalesce(sum(bp.amount_paid) filter (
      where lower(coalesce(bp.status,'')) in ('paid','completed','approved','succeeded')
    ),0)::numeric as gross_revenue
  from public.book_purchases bp
  group by bp.book_id
), reviews as (
  select
    br.book_id,
    count(*) filter (where br.status = 'published')::bigint as review_count,
    coalesce(avg(br.rating) filter (where br.status = 'published'),0)::numeric(4,2) as verified_rating
  from public.book_reviews br
  group by br.book_id
), events as (
  select
    me.book_id,
    count(*) filter (where me.event_type = 'book_impression')::bigint as impressions,
    count(*) filter (where me.event_type = 'book_click')::bigint as clicks,
    count(*) filter (where me.event_type = 'preview_started')::bigint as preview_starts,
    count(*) filter (where me.event_type = 'preview_completed')::bigint as preview_completions,
    count(*) filter (where me.event_type = 'checkout_started')::bigint as checkout_starts,
    count(*) filter (where me.event_type = 'reader_completed')::bigint as reader_completions
  from public.marketplace_events me
  group by me.book_id
)
select
  b.id as book_id,
  coalesce(p.verified_sales_count,0) as verified_sales_count,
  coalesce(p.refund_count,0) as refund_count,
  coalesce(p.gross_revenue,0) as gross_revenue,
  coalesce(r.review_count,0) as review_count,
  coalesce(r.verified_rating,0)::numeric(4,2) as verified_rating,
  coalesce(e.impressions,0) as impressions,
  coalesce(e.clicks,0) as clicks,
  coalesce(e.preview_starts,0) as preview_starts,
  coalesce(e.preview_completions,0) as preview_completions,
  coalesce(e.checkout_starts,0) as checkout_starts,
  coalesce(e.reader_completions,0) as reader_completions,
  case when coalesce(e.impressions,0) > 0
    then round((coalesce(e.clicks,0)::numeric / e.impressions) * 100, 2)
    else 0 end as click_through_rate,
  case when coalesce(e.preview_starts,0) > 0
    then round((coalesce(p.verified_sales_count,0)::numeric / e.preview_starts) * 100, 2)
    else 0 end as preview_to_purchase_rate
from public.books b
left join purchases p on p.book_id = b.id
left join reviews r on r.book_id = b.id
left join events e on e.book_id = b.id;

-- ============================================================
-- 6. BESTSELLER SCORE VERIFICABLE
-- ============================================================
create or replace view public.book_bestseller_scores as
with recent_sales as (
  select
    bp.book_id,
    count(*) filter (
      where lower(coalesce(bp.status,'')) in ('paid','completed','approved','succeeded')
        and coalesce(bp.paid_at,bp.created_at) >= now() - interval '24 hours'
    )::numeric as sales_24h,
    count(*) filter (
      where lower(coalesce(bp.status,'')) in ('paid','completed','approved','succeeded')
        and coalesce(bp.paid_at,bp.created_at) >= now() - interval '7 days'
    )::numeric as sales_7d,
    count(*) filter (
      where lower(coalesce(bp.status,'')) in ('paid','completed','approved','succeeded')
        and coalesce(bp.paid_at,bp.created_at) >= now() - interval '30 days'
    )::numeric as sales_30d
  from public.book_purchases bp
  group by bp.book_id
), recent_events as (
  select
    me.book_id,
    count(*) filter (where me.event_type = 'book_click' and me.occurred_at >= now() - interval '7 days')::numeric as clicks_7d,
    count(*) filter (where me.event_type = 'reader_completed' and me.occurred_at >= now() - interval '30 days')::numeric as completions_30d
  from public.marketplace_events me
  group by me.book_id
)
select
  b.id as book_id,
  coalesce(s.sales_24h,0) as sales_24h,
  coalesce(s.sales_7d,0) as sales_7d,
  coalesce(s.sales_30d,0) as sales_30d,
  coalesce(vm.verified_rating,0) as rating,
  coalesce(e.clicks_7d,0) as clicks_7d,
  coalesce(e.completions_30d,0) as completions_30d,
  round(
      coalesce(s.sales_24h,0) * 0.30
    + coalesce(s.sales_7d,0) * 0.25
    + coalesce(s.sales_30d,0) * 0.10
    + least(coalesce(vm.preview_to_purchase_rate,0),100) * 0.15
    + coalesce(vm.verified_rating,0) * 2 * 0.10
    + least(coalesce(e.completions_30d,0),100) * 0.10
  ,4) as bestseller_score
from public.books b
left join recent_sales s on s.book_id = b.id
left join recent_events e on e.book_id = b.id
left join public.book_verified_metrics vm on vm.book_id = b.id;

-- ============================================================
-- 7. ANALÍTICA DE AUTOR
-- ============================================================
create or replace view public.author_book_analytics as
select
  b.author_id,
  b.owner_user_id,
  b.id as book_id,
  b.slug,
  b.title,
  vm.verified_sales_count,
  vm.refund_count,
  vm.gross_revenue,
  vm.review_count,
  vm.verified_rating,
  vm.impressions,
  vm.clicks,
  vm.preview_starts,
  vm.preview_completions,
  vm.checkout_starts,
  vm.reader_completions,
  vm.click_through_rate,
  vm.preview_to_purchase_rate,
  bs.bestseller_score
from public.books b
join public.book_verified_metrics vm on vm.book_id = b.id
join public.book_bestseller_scores bs on bs.book_id = b.id;

-- ============================================================
-- 8. SEARCH 2.0: FTS + TRIGRAM + RANKING
-- ============================================================
create or replace function public.search_marketplace_books(
  p_query text,
  p_category text default null,
  p_limit integer default 24,
  p_offset integer default 0
)
returns table (
  book_id uuid,
  slug text,
  title text,
  subtitle text,
  cover_url text,
  primary_category text,
  primary_niche text,
  verified_rating numeric,
  verified_sales_count bigint,
  bestseller_score numeric,
  relevance numeric
)
language sql
stable
security invoker
set search_path = public
as $$
  with query_parts as (
    select
      nullif(trim(coalesce(p_query,'')), '') as raw_q,
      websearch_to_tsquery('simple', coalesce(nullif(trim(p_query),''), '')) as tsq
  ), candidates as (
    select
      b.*,
      vm.verified_rating,
      vm.verified_sales_count,
      bs.bestseller_score,
      setweight(to_tsvector('simple', coalesce(b.title,'')), 'A') ||
      setweight(to_tsvector('simple', coalesce(b.subtitle,'')), 'A') ||
      setweight(to_tsvector('simple', coalesce(array_to_string(b.keywords,' '),'')), 'B') ||
      setweight(to_tsvector('simple', coalesce(b.primary_category,'')), 'B') ||
      setweight(to_tsvector('simple', coalesce(b.primary_niche,'')), 'B') ||
      setweight(to_tsvector('simple', coalesce(b.description_short,'')), 'C') ||
      setweight(to_tsvector('simple', coalesce(b.description_long,'')), 'D') as document,
      qp.raw_q,
      qp.tsq
    from public.books b
    cross join query_parts qp
    left join public.book_verified_metrics vm on vm.book_id = b.id
    left join public.book_bestseller_scores bs on bs.book_id = b.id
    where lower(coalesce(b.status::text,'')) = 'published'
      and (
        p_category is null or trim(p_category) = '' or
        lower(coalesce(b.primary_category,'')) = lower(trim(p_category)) or
        lower(coalesce(b.primary_niche,'')) = lower(trim(p_category)) or
        lower(coalesce(b.secondary_category,'')) = lower(trim(p_category))
      )
  )
  select
    c.id,
    c.slug,
    c.title,
    c.subtitle,
    c.cover_url,
    c.primary_category,
    c.primary_niche,
    coalesce(c.verified_rating,0),
    coalesce(c.verified_sales_count,0),
    coalesce(c.bestseller_score,0),
    case
      when c.raw_q is null then coalesce(c.bestseller_score,0)
      else round((
          ts_rank_cd(c.document, c.tsq, 32) * 100
        + similarity(lower(coalesce(c.title,'')), lower(c.raw_q)) * 40
        + similarity(lower(coalesce(c.subtitle,'')), lower(c.raw_q)) * 15
        + least(coalesce(c.bestseller_score,0),100) * 0.05
      )::numeric, 4)
    end as relevance
  from candidates c
  where c.raw_q is null
     or c.document @@ c.tsq
     or similarity(lower(coalesce(c.title,'')), lower(c.raw_q)) > 0.15
     or similarity(lower(coalesce(c.subtitle,'')), lower(c.raw_q)) > 0.15
  order by relevance desc, c.title asc
  limit greatest(1, least(coalesce(p_limit,24),100))
  offset greatest(coalesce(p_offset,0),0);
$$;

-- ============================================================
-- 9. RECOMENDACIONES V1 EXPLICABLES
-- ============================================================
create or replace function public.recommend_marketplace_books(
  p_user_id uuid,
  p_limit integer default 12
)
returns table (
  book_id uuid,
  slug text,
  title text,
  cover_url text,
  reason text,
  score numeric
)
language sql
stable
security invoker
set search_path = public
as $$
  with purchased as (
    select distinct b.primary_category, b.primary_niche
    from public.book_purchases bp
    join public.books b on b.id = bp.book_id
    where bp.user_id = p_user_id
      and lower(coalesce(bp.status,'')) in ('paid','completed','approved','succeeded')
  ), already_owned as (
    select distinct bp.book_id
    from public.book_purchases bp
    where bp.user_id = p_user_id
      and lower(coalesce(bp.status,'')) in ('paid','completed','approved','succeeded')
  )
  select
    b.id,
    b.slug,
    b.title,
    b.cover_url,
    case
      when exists (
        select 1 from purchased p
        where p.primary_category is not null
          and lower(p.primary_category) = lower(b.primary_category)
      ) then 'Porque lees esta categoría'
      when exists (
        select 1 from purchased p
        where p.primary_niche is not null
          and lower(p.primary_niche) = lower(b.primary_niche)
      ) then 'Relacionado con tus lecturas'
      else 'Tendencia en LibroSeller'
    end as reason,
    round((
      coalesce(bs.bestseller_score,0) * 0.55
      + coalesce(vm.verified_rating,0) * 5 * 0.15
      + case when exists (
          select 1 from purchased p
          where lower(coalesce(p.primary_category,'')) = lower(coalesce(b.primary_category,''))
        ) then 20 else 0 end
      + case when exists (
          select 1 from purchased p
          where lower(coalesce(p.primary_niche,'')) = lower(coalesce(b.primary_niche,''))
        ) then 10 else 0 end
    )::numeric,4) as score
  from public.books b
  left join public.book_bestseller_scores bs on bs.book_id = b.id
  left join public.book_verified_metrics vm on vm.book_id = b.id
  where lower(coalesce(b.status::text,'')) = 'published'
    and not exists (select 1 from already_owned ao where ao.book_id = b.id)
  order by score desc, b.created_at desc nulls last
  limit greatest(1, least(coalesce(p_limit,12),50));
$$;

-- ============================================================
-- 10. RLS / PRIVILEGIOS
-- ============================================================
alter table public.book_reviews enable row level security;
alter table public.marketplace_events enable row level security;
alter table public.epub_preflight_reports enable row level security;
alter table public.book_editorial_versions enable row level security;

drop policy if exists "Public can read published book reviews" on public.book_reviews;
create policy "Public can read published book reviews"
on public.book_reviews for select
to anon, authenticated
using (status = 'published');

drop policy if exists "Users can manage own reviews" on public.book_reviews;
create policy "Users can manage own reviews"
on public.book_reviews for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Eventos se insertan únicamente desde el servidor con service role.
revoke all on table public.marketplace_events from anon, authenticated;
revoke all on table public.epub_preflight_reports from anon, authenticated;
revoke all on table public.book_editorial_versions from anon, authenticated;
grant all on table public.marketplace_events to service_role;
grant all on table public.epub_preflight_reports to service_role;
grant all on table public.book_editorial_versions to service_role;
grant all on table public.book_reviews to service_role;

grant select on public.book_verified_metrics to anon, authenticated, service_role;
grant select on public.book_bestseller_scores to anon, authenticated, service_role;
grant select on public.author_book_analytics to service_role;
grant execute on function public.search_marketplace_books(text,text,integer,integer) to anon, authenticated, service_role;
grant execute on function public.recommend_marketplace_books(uuid,integer) to authenticated, service_role;

comment on table public.book_reviews is 'Reseñas de libros con verificación de compra calculada en servidor.';
comment on table public.marketplace_events is 'Telemetría first-party para funnel, recomendaciones y analítica de LibroSeller.';
comment on table public.epub_preflight_reports is 'Resultados del control editorial automático previo a publicación.';
comment on table public.book_editorial_versions is 'Historial inmutable de versiones editoriales por libro.';
comment on view public.book_verified_metrics is 'Métricas públicas derivadas exclusivamente de actividad verificable.';
comment on view public.book_bestseller_scores is 'Ranking transparente basado en ventas, conversión, rating y finalización de lectura.';

commit;
